name: taxi_esil
description: "MEKEN passenger, driver, delivery, and intercity transport app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_map: ^8.0.0
  flutter_map_maplibre: ^0.0.5
  maplibre: ^0.3.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.6.0
  video_player: ^2.8.6
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  mask_text_input_formatter: ^2.9.0
  web: ^1.0.0
  shared_preferences: ^2.3.2
  firebase_messaging: ^16.5.0 #
  url_launcher: ^6.3.2
  flutter_secure_storage: ^11.0.0
  flutter_tts: ^4.2.5
  audioplayers: 6.5.1
  wakelock_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/splash.mp4
    - assets/logo.png
    - assets/meken_logo_transparent.png
    - assets/audio/navigation/
    - assets/audio/navigation/ru/
    - assets/audio/navigation/kk/
    - assets/audio/navigation/en/
