// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2m30Q9BzBEXxA9Rb9NAWj9Lid-JVSIw',
    appId: '1:416483778124:web:b3d88d9cdc52f1daa41ee9',
    messagingSenderId: '416483778124',
    projectId: 'taxi-esil',
    authDomain: 'taxi-esil.firebaseapp.com',
    databaseURL: 'https://taxi-esil-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-esil.firebasestorage.app',
    measurementId: 'G-9PKB69CTPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKIkxZ63bGbdLDTyly0eiuUN9U0qziY0',
    appId: '1:416483778124:android:82418192851dc65ca41ee9',
    messagingSenderId: '416483778124',
    projectId: 'taxi-esil',
    databaseURL: 'https://taxi-esil-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-esil.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXbdVC5qgdVSx24Ca5toCmnOFyth71wk',
    appId: '1:416483778124:ios:82747d59e6d9c2cda41ee9',
    messagingSenderId: '416483778124',
    projectId: 'taxi-esil',
    databaseURL: 'https://taxi-esil-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-esil.firebasestorage.app',
    iosBundleId: 'com.example.taxiEsil',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXbdVC5qgdVSx24Ca5toCmnOFyth71wk',
    appId: '1:416483778124:ios:82747d59e6d9c2cda41ee9',
    messagingSenderId: '416483778124',
    projectId: 'taxi-esil',
    databaseURL: 'https://taxi-esil-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-esil.firebasestorage.app',
    iosBundleId: 'com.example.taxiEsil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG2m30Q9BzBEXxA9Rb9NAWj9Lid-JVSIw',
    appId: '1:416483778124:web:8aba5218e9d4e7e7a41ee9',
    messagingSenderId: '416483778124',
    projectId: 'taxi-esil',
    authDomain: 'taxi-esil.firebaseapp.com',
    databaseURL: 'https://taxi-esil-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-esil.firebasestorage.app',
    measurementId: 'G-N8RLSNTYW4',
  );
}
